server:
  # port
  port: 8082
  servlet:
    context-path: /
spring:
  application:
    name: OnlineDocs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmd?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: mysqluser # doc
    password: mysqlpass # AliyunDocApplication
mybatis:
  mapper-locations: classpath*:/mapper/*.xml

config:
  jwt:
    secret: onlinedocseditor
    expire: 3600
    header: token